server:
    port: 0
spring:
    application:
        name: config-client-test
    cloud:
        config:
            name: ${spring.application.name}
            username: admin
            password: password
            uri: 'https://127.0.0.1:9876/'
            tls:
                enabled: true
                trust-store: 'classpath:truststore.pfx'
                trust-store-type: PKCS12
                trust-store-password: panamax
                #key-store: 'classpath:truststore.pfx'
                #key-store-type: PKCS12
                #key-store-password: panamax
                #key-password: panamax
    config:
        import: 'optional:configserver:https://127.0.0.1:9876/'

